### ISSUE TITLE
Nice fork! But where is the copyrights?

### ISSUE THREAD

**Issue by eminfedar** [maunalinux/mauna-about#1]
Hello,

It is nice to hear you forked [Pardus's](pardus.org.tr) programs to use in your distro. You are free to go!

But the programs **we developed from zero** and **licensed with GPL3** does not exists here: https://github.com/pardus/pardus-about/blob/master/debian/copyright (you erased the names of the real developers)

This is not forking an open source project. This is kinda stealing :). The licensed core program should be respected.

Please do not remove the real authors from the project. Meanwhile **you can freely embed your distro's name** everywhere on the program(that's why forking exists :))!

Have a nice day, keep up the good work!

**Comment by maunalinux** [comment]
Hello!

My sincere apologies and I am already reviewing and organizing everything and due credits will be added to the authors and their respective applications.

Also have a great work and have a good 2024!
